events {}

http {
  server {
    listen 80;

    location /health {
      proxy_pass http://backend:8000/health;
    }

    location /api/ {
      proxy_pass http://backend:8000;
    }

    location / {
      proxy_pass http://frontend:5173;
    }
  }
}
